vn 1

text "MonsterDoor 0 hp:" 255 255 255
text "map.zombieDoor0_HP: $map.zombieDoor0_HP" 255 255 255
text "map.tickSwitch: $map.tickSwitch" 255 255 255
text "map.currentRound: $map.currentRound" 255 255 255
text "map.roundsToWin: $map.roundsToWin" 255 255 255
text "map.baseTicksToNextRound: $map.baseTicksToNextRound" 255 255 255
text "map.ticksToNextRound: $map.ticksToNextRound" 255 255 255
text "map.ticksSinceMapStart: $map.ticksSinceMapStart" 255 255 255

vn 0
map return